spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_policy_db?createDatabaseIfNotExist=true
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
gemini:
  api:
    key: AIzaSyAw1KaqukUyme116Y3zBcz53Hsjfjg-B1A

